---
driver:
  name: vagrant
  customize:
    memory: 1024
  require_chef_omnibus: true

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
    run_list:
      - recipe[ubuntu::default]
      - recipe[chef-apt-docker::default]
  - name: centos
    driver:
      box: bento/centos-7.2
    run_list:
      - recipe[yum-epel::default]
      - recipe[chef-yum-docker::default]

suites:
  - name: drone-0.5
    run_list:
      - recipe[drone::default]
      - recipe[drone::agent]
    attributes:
      drone:
        agent:
          config:
            I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
            I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
            drone_server: ws://10.0.2.15/ws/broker
        docker:
          daemon:
            log_level: debug
        server:
          config:
            I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
            I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
            DRONE_GITHUB: true
            DRONE_GITHUB_CLIENT: GH_CLIENT
            DRONE_GITHUB_SECRET: GH_SECRET

  - name: drone-0.5-docker-overrides
    run_list:
      - recipe[drone::default]
      - recipe[drone::agent]
    attributes:
      drone:
        agent:
          config:
            I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
            I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
            drone_server: ws://10.0.2.15/ws/broker
          network_mode: host
        docker:
          bridge_ip: 192.168.1.1/24
          cidr_v4: 192.168.0.0/16
          daemon:
            log_level: debug
          version: '17.05.0'
        server:
          config:
            I_UNDERSTAND_I_AM_USING_AN_UNSTABLE_VERSION: true
            I_AGREE_TO_FIX_BUGS_AND_NOT_FILE_BUGS: true
            DRONE_GITHUB: true
            DRONE_GITHUB_CLIENT: GH_CLIENT
            DRONE_GITHUB_SECRET: GH_SECRET
            drone_server_addr: :80
          network_mode: host
          port: '80'

  - name: drone-0.6
    run_list:
      - recipe[drone::default]
      - recipe[drone::agent]
    attributes:
      drone:
        agent:
          config:
            drone_server: ws://10.0.2.15/ws/broker
        docker:
          daemon:
            log_level: debug
        server:
          config:
            DRONE_HOST: http://10.0.2.15
            DRONE_GITHUB: true
            DRONE_GITHUB_CLIENT: GH_CLIENT
            DRONE_GITHUB_SECRET: GH_SECRET
        version: '0.6'

  - name: drone-custom
    excludes:
      - centos
    driver:
      network:
        - ["forwarded_port", {guest: 8080, host: 8080}]
        - ["forwarded_port", {guest: 9080, host: 9080}]
    run_list:
      - recipe[gogs::default]
      - recipe[fake::gogs]
      - recipe[drone::default]
      - recipe[drone::agent]
    attributes:
      drone:
        agent:
          config:
            drone_server: ws://10.0.2.15:9080/ws/broker
        docker:
          daemon:
            log_level: debug
        server:
          config:
            drone_host: http://10.0.2.15:9080
            drone_debug: true
            drone_gogs: true
            drone_gogs_url: http://10.0.2.15:8080
            drone_open: true
          port: '9080:8000'
        version: '0.6'
      gogs:
        config:
          server:
            DOMAIN: 10.0.2.15
            HTTP_ADDR: 10.0.2.15
        version: '0.9.97'
