---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024

driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
    require_chef_omnibus: latest
- name: ubuntu-12.10
  driver_config:
    box: opscode-ubuntu-12.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.10_chef-provisionerless.box
    require_chef_omnibus: latest
- name: ubuntu-13.04
  driver_config:
    box: opscode-ubuntu-13.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.04_chef-provisionerless.box
    require_chef_omnibus: latest
- name: ubuntu-13.10
  driver_config:
    box: opscode-ubuntu-13.10
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box
    require_chef_omnibus: latest

suites:
  - name: default
    run_list:
      - recipe[drone::default]
  - name: nginx
    run_list:
      - recipe[drone::default]
      - recipe[drone::nginx]
    attributes:
      drone:
        address: '127.0.0.1'
        port: '5000'
