---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024
  require_chef_omnibus: latest

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.0
  - name: centos-6.5
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[drone::default]
  - name: config
    run_list:
      - recipe[drone::default]
    attributes:
      drone:
        config:
          server:
            port: ':443'
          worker:
            nodes:
              - "unix:///var/run/docker.sock"
              - "unix:///var/run/docker.sock"
