---
driver_plugin: vagrant

driver_config:
  customize:
    memory: 1024
  require_chef_omnibus: latest

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-13.10
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[drone::default]
  - name: droned_opts
    run_list:
      - recipe[drone::default]
    attributes:
      drone:
        droned_opts: --port=:443 --workers=2
    includes:
      - ubuntu-14.04
