AlignParameters:
  Enabled: false

Style/LineLength:
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'

Encoding:
  Enabled: false

StringLiterals:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Exclude:
    - metadata.rb
