LineLength:
  Max: 150

AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

StringLiterals:
  Enabled: false

SpaceBeforeFirstArg:
  Exclude:
    - metadata.rb

WordArray:
  Enabled: false
